pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                bat 'echo "Building the project..."'
                bat 'echo "Build completed."'
            }
        }
    }
}