pipeline {
    agent any

    stages {
        stage('Build and test') {
            steps {
                echo 'Building and testing...'

                dir('test-dev-ops') {
                    bat 'npm install'
                    bat 'npm run build'
                    echo 'run npm test if you have tests'
                }
            }
        }
        
    }

    post {
        always {
            echo 'Cleaning up workspace...'
        }
    }
}